name: Deploy to GitHub Pages

on:
  # 當推送程式碼到 main 分支時觸發 (如果你的預設分支是 master，請將 main 改為 master)
  push:
    branches: ["main"]

# 設定 GITHUB_TOKEN 的權限，以允許部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 允許一個並發的部署，跳過在進行中和最新排隊之間的執行
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build
        run: npm run build
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
